import React, { useState } from 'react';
import { useFearless } from '../../services/store';
import { CreditCard, Check, X, RefreshCw, KeyRound } from 'lucide-react';

export const StripeCheckoutModal: React.FC = () => {
  const {
    stripeModalOpen,
    setStripeModalOpen,
    parent,
    handleStripeSubscription,
    redeemPairingCode,
    triggerWebhookEvent
  } = useFearless();

  const [emailInput, setEmailInput] = useState(parent.email || 'parent@fearlessfootballer.com');
  const [athleteNameInput, setAthleteNameInput] = useState('Alex Sterling');
  const [pairingInput, setPairingInput] = useState('');
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);

  if (!stripeModalOpen) return null;

  const handleCheckout = () => {
    setIsProcessing(true);
    setTimeout(() => {
      const code = handleStripeSubscription(emailInput, athleteNameInput);
      setIsProcessing(false);
      setActionSuccess(`Stripe Checkout Successful! Family pairing code generated: ${code}`);
    }, 600);
  };

  const handleTestPairingCode = () => {
    const success = redeemPairingCode(pairingInput);
    if (success) {
      setActionSuccess(`Family pairing verified! Fearless HQ successfully linked to Parent Dashboard.`);
    } else {
      setActionSuccess(`Invalid pairing code. Please enter the exact code generated by the parent.`);
    }
  };

  const handleSimulateWebhookCancel = () => {
    triggerWebhookEvent({
      id: `evt_${Date.now()}`,
      type: 'customer.subscription.deleted',
      data: {
        object: {
          id: parent.stripeCustomerId || 'cus_demo',
          customer: parent.stripeCustomerId || 'cus_demo'
        }
      }
    });
    setActionSuccess('Stripe Webhook Received: customer.subscription.deleted -> Status updated to "canceled"');
  };

  const handleSimulateWebhookRenew = () => {
    triggerWebhookEvent({
      id: `evt_${Date.now()}`,
      type: 'customer.subscription.updated',
      data: {
        object: {
          id: parent.stripeCustomerId || 'cus_demo',
          status: 'active'
        }
      }
    });
    setActionSuccess('Stripe Webhook Received: customer.subscription.updated -> Status restored to "active"');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-md p-4 animate-in fade-in">
      <div className="w-full max-w-lg bg-brand-dark border border-brand-border rounded-3xl p-6 relative max-h-[90vh] overflow-y-auto shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-brand-border mb-4">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-xl bg-brand-blue/20 text-brand-cyan">
              <CreditCard className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-extrabold text-white">
                Stripe Billing & Family Pairing
              </h3>
              <span className="text-[10px] text-brand-silver">
                Native Membership & Instant Account Sync
              </span>
            </div>
          </div>
          <button
            onClick={() => {
              setStripeModalOpen(false);
              setActionSuccess(null);
            }}
            className="w-8 h-8 rounded-full bg-brand-card hover:bg-brand-cardHover border border-brand-border flex items-center justify-center text-brand-silver hover:text-white"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Feedback alert */}
        {actionSuccess && (
          <div className="p-3 rounded-xl bg-brand-blue/20 border border-brand-cyan/40 text-brand-cyan text-xs font-semibold mb-4 flex items-start gap-2">
            <Check className="w-4 h-4 shrink-0 text-brand-cyan mt-0.5" />
            <p>{actionSuccess}</p>
          </div>
        )}

        {/* Section 1: Stripe Checkout (Parent Membership) */}
        <div className="bg-brand-card border border-brand-border rounded-2xl p-4 mb-4">
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">
              1. Parent Value-Based Membership
            </h4>
            <span className="text-[10px] font-bold text-brand-cyan bg-brand-cyan/10 px-2 py-0.5 rounded">
              Current: {parent.subscriptionStatus}
            </span>
          </div>
          <p className="text-[11px] text-brand-silver mb-3">
            Long-term mental health ROI. Direct Stripe checkout with zero app-store transaction friction.
          </p>

          <div className="space-y-2 mb-3">
            <div>
              <label className="text-[10px] font-semibold text-brand-silver block mb-1">
                Parent Billing Email:
              </label>
              <input
                type="email"
                value={emailInput}
                onChange={e => setEmailInput(e.target.value)}
                className="w-full bg-brand-dark border border-brand-border rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-blue"
              />
            </div>
            <div>
              <label className="text-[10px] font-semibold text-brand-silver block mb-1">
                Youth Athlete Name:
              </label>
              <input
                type="text"
                value={athleteNameInput}
                onChange={e => setAthleteNameInput(e.target.value)}
                className="w-full bg-brand-dark border border-brand-border rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-blue"
              />
            </div>
          </div>

          <button
            onClick={handleCheckout}
            disabled={isProcessing}
            className="w-full py-2.5 px-4 rounded-xl bg-gradient-to-r from-brand-blue to-brand-cyan text-black font-extrabold text-xs uppercase tracking-wider flex items-center justify-center gap-2 hover:opacity-95 shadow-md transition-all"
          >
            <CreditCard className="w-4 h-4" />
            <span>{isProcessing ? 'Connecting to Stripe...' : 'Simulate Stripe Checkout'}</span>
          </button>
        </div>

        {/* Section 2: Family Pairing Redemption */}
        <div className="bg-brand-card border border-brand-border rounded-2xl p-4 mb-4">
          <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-1 flex items-center gap-1.5">
            <KeyRound className="w-3.5 h-3.5 text-brand-cyan" />
            2. Redeem 6-Digit Pairing Code on Athlete Device
          </h4>
          <p className="text-[11px] text-brand-silver mb-3">
            Athletes enter the code to bind their Fearless HQ to the parent dashboard without payment credentials.
          </p>

          <div className="flex gap-2">
            <input
              type="text"
              value={pairingInput}
              onChange={e => setPairingInput(e.target.value)}
              placeholder="e.g. FEAR-4892"
              className="flex-1 bg-brand-dark border border-brand-border rounded-xl px-3 py-2 text-xs font-mono uppercase text-white focus:outline-none focus:border-brand-blue"
            />
            <button
              onClick={handleTestPairingCode}
              className="py-2 px-3 rounded-xl bg-brand-cardHover border border-brand-border text-white text-xs font-bold hover:border-brand-cyan transition-colors"
            >
              Verify Code
            </button>
          </div>
        </div>

        {/* Section 3: Stripe Webhook Simulator */}
        <div className="bg-brand-dark/90 border border-brand-border rounded-2xl p-4">
          <div className="flex items-center gap-1.5 text-[10px] font-bold text-brand-silver uppercase tracking-wider mb-2">
            <RefreshCw className="w-3 h-3 text-brand-cyan" />
            <span>Stripe Webhook Event Simulation</span>
          </div>
          <div className="grid grid-cols-2 gap-2">
            <button
              onClick={handleSimulateWebhookRenew}
              className="p-2 rounded-xl bg-brand-card hover:bg-brand-cardHover border border-brand-border text-[11px] font-semibold text-emerald-400 text-left transition-colors"
            >
              Simulate: subscription.updated (active)
            </button>
            <button
              onClick={handleSimulateWebhookCancel}
              className="p-2 rounded-xl bg-brand-card hover:bg-brand-cardHover border border-brand-border text-[11px] font-semibold text-rose-400 text-left transition-colors"
            >
              Simulate: subscription.deleted (cancel)
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
